### PR TITLE
Mostly UI updates

### PR DESCRIPTION
**Pull request by ITBlandMCT**
When adding groups to policies, there are now two **Add groups** buttons, one under **Included** and one under **Excluded**; changed to "under **Included groups** select **Add groups**, as the **Excluded groups** option is the easier one to see.
image

In 0602, there was a case of a space before the closing "\*\*", causing the asterisks to show instead of adding **BOLD** format.
image

Addressing #86: In 0901, WS3 is not a member of the group used, changed to WS2 and sign in as Diego instead of Aaron (for simplicity, Diego is already signed in on WS2).
>Note, each update was pushed separately, so you can reject those that you don't want.

Thx!

### CODE REVIEW

**Comment by ITBlandMCT** [comment]
Oh, in 0403, in Step 4 of Task 3, we clicked on the “Deployment Types” tab, we need to get back to “Summary” to see the “Content Status” link.
The previously added step in 0404, Ex 1, Task 2 means that step 11 needs to be updated to "Repeat steps 2-10"

**Comment by ITBlandMCT** [comment]
0502, Task 4- ([This update](https://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops/pull/87/commits/ad0054962a21f2553a14fedd27c2e4b489ad8222)) in the pull request removes the unnecessary AD Sync in the sspr lab (mentioned in #85 )

**Comment by ITBlandMCT** [comment]
[This update](https://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops/commit/01973b0763f7d9e635e5ce458654c725e51bfa78) adds this:
, replacing **_\<yourtenant\>_** with the tenant name provided to you,
To the yourtenant.sharepoint.com URL

**Comment by ITBlandMCT** [comment]
[This update](https://github.com/MicrosoftLearning/MD-101T00-ManagingModernDesktops/commit/01973b0763f7d9e635e5ce458654c725e51bfa78) adds this:
, replacing **_\<yourtenant\>_** with the tenant name provided to you,
To the yourtenant.sharepoint.com URL

**Comment by ITBlandMCT** [comment]
Added corrections for #89 and #90

**Comment by BrianHinkelman** [comment]
Thanks, we are looking into these.

**Comment by BrianHinkelman** [comment]
Accepted, thank you.

**Pull request merged**
