### PR TITLE
Update 0102-Using Azure AD Connect to connect AD DS to Azure AD.md

### PR DESCRIPTION
**Pull request by hales1991**

### CODE REVIEW

**Comment by BrianHinkelman** [comment]
This change is incorrect.  There is no "portal menu" to select, the instructions are correct, as written.

**Comment by hales1991** [comment]
I can provide screenshot. It’s another way to reach the same point. However if you would like to keep it as is that’s fine too.


Rob

Sent from my iPhone

On Mar 2, 2021, at 11:49, BrianHinkelman <notifications@github.com> wrote:

﻿

This change is incorrect. There is no "portal menu" to select, the instructions are correct, as written.

**Comment by BrianHinkelman** [comment]
Yes, please submit a screenshot.

**Comment by hales1991** [comment]
I see where you’re coming from. I don’t see it when I use edge or chrome on my computer but in the lab environment (maybe because of the screen size/resolution?) in the top left when you select on the navigation pane there is a orange hyperlink pointing you in that direction and because I don’t have access to the lab environment I can’t replicate it. I apologize for any inconvience. You can have the lab instructions however you see fit, that’s just what I saw while doing the labs.

Rob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BrianHinkelman** [comment]
If there is a different experience within the lab environment - such as the screen resolution - we definitely want to be aware of that, and tweak the steps if necessary.  I'm just not seeing what you're describing - I will see if I can repro this in the lab view.

**Comment by BrianHinkelman** [comment]
Unable to repro in student environment.

**Comment by hales1991** [comment]
Ok. Well thank you for verifying. If I come across it I’ll let you know.

Rob

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by BrianHinkelman** [comment]
After some additional resizing and lower resolution settings, I was able to see the experience you are referring to. We'll have to review options for accomodating this since the experience will vary depending on student device resolution.  Thanks for being diligent on this, and please forgive my haste in rejecting this!

**Comment by hales1991** [comment]
All good! These labs are our babies. I get it.

Rob

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Pull request closed without merging**
